/*
 * This file is generated by jOOQ.
 */
package com.quarki.db.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record Foo(
    String name,
    Integer[] nums,
    LocalDate date,
    Integer bar
) implements Serializable {

    private static final long serialVersionUID = 1L;


    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Foo other = (Foo) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.nums == null) {
            if (other.nums != null)
                return false;
        }
        else if (!Arrays.equals(this.nums, other.nums))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        if (this.bar == null) {
            if (other.bar != null)
                return false;
        }
        else if (!this.bar.equals(other.bar))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.nums == null) ? 0 : Arrays.hashCode(this.nums));
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.bar == null) ? 0 : this.bar.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Foo (");

        sb.append(name);
        sb.append(", ").append(Arrays.toString(nums));
        sb.append(", ").append(date);
        sb.append(", ").append(bar);

        sb.append(")");
        return sb.toString();
    }
}
