greeting:
  message: "hello"

quarkus:
  datasource:
    devservices:
      enabled: true
      port: 5432
  banner:
    enabled: false

  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.sql
  jooq:
    dialect: postgresql