/*
 * This file is generated by jOOQ.
 */
package com.quarki.db.jooq;


import com.quarki.db.jooq.tables.Foo;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = Foo.FOO;
}
