/*
 * This file is generated by jOOQ.
 */
package com.quarki.db.jooq.tables;


import com.quarki.db.jooq.Public;
import com.quarki.db.jooq.tables.records.FooRecord;

import java.time.LocalDate;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Foo extends TableImpl<FooRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.foo</code>
     */
    public static final Foo FOO = new Foo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FooRecord> getRecordType() {
        return FooRecord.class;
    }

    /**
     * The column <code>public.foo.name</code>.
     */
    public final TableField<FooRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.foo.nums</code>.
     */
    public final TableField<FooRecord, Integer[]> NUMS = createField(DSL.name("nums"), SQLDataType.INTEGER.getArrayDataType(), this, "");

    /**
     * The column <code>public.foo.date</code>.
     */
    public final TableField<FooRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    private Foo(Name alias, Table<FooRecord> aliased) {
        this(alias, aliased, null);
    }

    private Foo(Name alias, Table<FooRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.foo</code> table reference
     */
    public Foo(String alias) {
        this(DSL.name(alias), FOO);
    }

    /**
     * Create an aliased <code>public.foo</code> table reference
     */
    public Foo(Name alias) {
        this(alias, FOO);
    }

    /**
     * Create a <code>public.foo</code> table reference
     */
    public Foo() {
        this(DSL.name("foo"), null);
    }

    public <O extends Record> Foo(Table<O> child, ForeignKey<O, FooRecord> key) {
        super(child, key, FOO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Foo as(String alias) {
        return new Foo(DSL.name(alias), this);
    }

    @Override
    public Foo as(Name alias) {
        return new Foo(alias, this);
    }

    @Override
    public Foo as(Table<?> alias) {
        return new Foo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Foo rename(String name) {
        return new Foo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Foo rename(Name name) {
        return new Foo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Foo rename(Table<?> name) {
        return new Foo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Integer[], LocalDate> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super Integer[], ? super LocalDate, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super Integer[], ? super LocalDate, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
